server:
  port: 8001

spring:
  boot:
    admin:
      client:
        url: http://localhost:8000
  application:
    name: spring-boot-admin-client

management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  file:
    name: sbadc.log
