server:
  port: 8001

spring:
  boot:
    admin:
      client:
        instance:
          # sba server use ip invoke actuator api
          prefer-ip: true
        # sba server url
        url: http://localhost:8000
  application:
    name: spring-boot-admin-client

management:
  info:
    git:
      mode: full
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  file:
    name: ./sbadc.log
  config: classpath:logback-sbadc.xml

info:
  tags:
    environment: your-profile
