server:
  port: ${SBADC_SERVER_PORT:8001}

spring:
  boot:
    admin:
      client:
        instance:
          # sba server use ip invoke actuator api
          prefer-ip: true
        # sba server url
        url: ${SBAC_URL:http://localhost:8000}
  application:
    name: spring-boot-admin-client
    admin:
      enabled: true
  jmx:
    enabled: true

management:
  info:
    env:
      enabled: true
    git:
      mode: full
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

logging:
  file:
    name: ./sbadc.log
  config: classpath:logback-sbadc.xml

info:
  tags:
    environment: your-profile

app:
  config:
    name: spring-boot-admin-demo测试