server:
  port: 8000

management:
  endpoints:
    enabled-by-default: false

spring:
  application:
    name: spring-boot-admin-server
  boot:
    admin:
      instance-proxy:
        # Do not carry these request headers
        ignored-headers:
          - User-Agent
          - Cookie
          - Set-Cookie
          - Authorization
      ui:
        title: SBA-demo